version: '3.8'

services:
  valkey:
    container_name: cpe-guesser-db
    image: valkey/valkey:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - valkey_data:/data
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - cpe-guesser-net

networks:
  cpe-guesser-net:
    driver: bridge
    internal: false

volumes:
  valkey_data: 